include:
  - board: seeeduino_xiao_ble
    shield: rodeoman_left rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: rodeoman_right rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
